Revert "media-video/pipewire: Bump v.0.3.56"
This reverts commit 498da4065e3a44403fc28718564159c7b812b8ec.

Revert for now because pipewire fail with this error:
```
/usr/include/linux/net_tstamp.h:158:2: error: unknown type name
'clockid_t'
```
that requires upgrade of linux-header package.